source: GREEN

output_filename: output
output_sheetname: sheet1

column_map:
  - key: status
    column: A
    tag: system

  - key: company
    column: B
    tag: list

  - key: people
    column: C
    tag: list

  - key: capitalstock
    column: D
    tag: indivisual

  - key: recruitmenturl
    column: E
    tag: list

  - key: website
    column: F
    tag: research

  - key: inquiry
    column: G
    tag: research